### ISSUE TITLE
Report unexpected exceptions

### ISSUE THREAD

**Issue by ammongit** [strinking/futaba#101]
Add a config file setting that uploads traceback files into a debugging channel. Should also provide information on where the error occurred.

**Comment by Ma-wa-re** [comment]
Yeah, I would have it for large errors only though. No need to do the processing on it for like 3-4 lines

**Comment by ammongit** [comment]
"Large" errors? I feel like any unexpected exception would be worth investigating, since it's not getting caught by `CommandFailed` or other handlers.

**Comment by Ma-wa-re** [comment]
Yeah, It should still go to the channel but what I meant was errors that are like 3-4 lines should just be sent as is, larger error messages should be uploaded to the paste service
