### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by nitros12** [strinking/futaba#170]
This looks incorrect

https://github.com/strinking/futaba/blob/35a004b1362408d79f4ea930af1ed17096056d69/futaba/client.py#L186-L205

Also, an issue with using the guild remove event: guild remove events can be fired when discord has server issues and guilds start dropping out, I would suggest keeping track of the last event from a guild and doing a cleanup of guilds with no events fired after some period of time to prevent the accidental deletion.

**Comment by Ma-wa-re** [comment]
Good spot that should be `self.sql.guilds.remove_guild(guild)`. If you want to make a PR for it that would be an easy fix!

**Comment by ammongit** [comment]
I'm not sure if a disconnect could delete all the guild data, there seems to be a separate part of the API for disconnects: https://discordpy.readthedocs.io/en/rewrite/api.html#discord.on_guild_unavailable

**Comment by nitros12** [comment]
d.py should be handling testing for the guild being unavailable or actually leaving, however in the past I've personally had problems with the event still being fired.
