### ISSUE TITLE
Remove on_guild_leave handlers and functions

### ISSUE THREAD

**Issue by ammongit** [strinking/futaba#174]
(Context: #170)

Since it's much more likely we accidentally remove futaba or a guild removes her then readds her than us actually being done using the bot entirely, removing guild information on removal is potentially more harmful than the benefits of saving space on the database.

cc: @nitros12 @Ma-wa-re

**Comment by Ma-wa-re** [comment]
I still think it should be cleared at some point, if possible could it be removed if the bot is not added back to the guild after a set amount of time?

**Comment by ammongit** [comment]
We could modify the `guilds` table to store the last date the bot was connected to it, and if the time is greater than 3 months we could run the delete hooks. Just add a navi task to check it every week or so.

**Comment by Ma-wa-re** [comment]
Sounds good

**Comment by ammongit** [comment]
Fixed #278
