### ISSUE TITLE
Auto-logging of manual punishments

### ISSUE THREAD

**Issue by ammongit** [strinking/futaba#20]
Right now if a staff right-clicks to kick or ban, we have no visible record of it other than the audit log. This can be confusing. Instead, the bot should always log kick or ban events as if performed with `!kick` or `!ban`. However, the bot should also include a reminder to the person in question to use the proper command instead.

**Comment by Ma-wa-re** [comment]
This has been done in #56 however it does not currently remind the person in question. Need to have a discussion on if it is needed as if we are logging it anyways why do we need to use the command

**Comment by ammongit** [comment]
In the future we might change the behavior of how it works. In fact, we
already do this in part by making the reason non optional.

**Comment by ammongit** [comment]
We will not be adding the "message the person" feature at this time.
