### ISSUE TITLE
Mounting paths to DMs

### ISSUE THREAD

**Issue by robstolarz** [strinking/futaba#208]
As a moderator who likes to be notified of more things than most people do, I'd like to be able to mount logger paths to my own DMs. This would mean I'd be able to get instant notifications about things only I care about, without disturbing or notifying others.

**Comment by ammongit** [comment]
Only moderators should be able to able to add journals paths for themselves, and only for guilds they are mods in. Otherwise there is the potential for private information getting leaked.
