### ISSUE TITLE
Add command to perform a unicode repr

### ISSUE THREAD

**Issue by ammongit** [strinking/futaba#226]
We have the `unicode_repr()` function in `unicode.py`. We should have a misc cog command that runs that command on the passed string.

**Comment by raylu** [comment]
https://github.com/MoreOutput/RockMUD/blob/master/src/commands.js#L33 uses https://github.com/garabik/unicode (packaged in debian)

**Comment by ammongit** [comment]
Seems like a nice CLI tool, but I don't see that module being very useful to us, we can fetch the information using the `unicodedata` module.
