### ISSUE TITLE
Able to get member while having dunce hat if they agree in #join

### ISSUE THREAD

**Issue by Rageoholic** [strinking/futaba#257]
Recently a member who had dunce hat left the server and later rejoined. The bot correctly gave dunce hat back to the member but allowed them to agree to the server rules which gave them back member. It seems that we need to have a specific way to get member such that if something would conflict with it its instead added to the saved roles.

**Comment by ammongit** [comment]
This will require:

1. Checking for "guest" in !agree when it's unset.
2. Ensuring reapply always takes precedence.

**Comment by ammongit** [comment]
@Rageoholic provisionally closed, if this happens again reopen the issue.
