### ISSUE TITLE
Cannot refresh jail time 

### ISSUE THREAD

**Issue by robstolarz** [strinking/futaba#271]
https://github.com/strinking/futaba/blob/6b301977726eaaee71454cbc910ae9b1b7520592/futaba/cogs/moderation/core.py#L107-L119, called from https://github.com/strinking/futaba/blob/6b301977726eaaee71454cbc910ae9b1b7520592/futaba/cogs/moderation/core.py#L255-L259, checks to make sure that someone does not already have overriding roles before applying a new set. However, because of this check, jail time cannot easily be refreshed or changed once it is set. Instead, an error like "Cannot add a new overriding role to \<user> because they already have \<role>" is presented.

Would it make sense to alter this check to see if the new overriding roles are the same as the old ones and, if so, allow the check to pass?

Or perhaps these functions should be merged to attempt to add the overriding roles, and fail if an override already exists and is different than the new one?

**Comment by ammongit** [comment]
Related to #267

**Comment by ammongit** [comment]
Checking to make sure the existing overriding role is `None` or the same makes sense. However modifying the actual timer is part of the linked issue.

**Comment by ammongit** [comment]
Multiple overriding roles were added in #298. Because the core issue this card is referring to exists in #267, I am closing this as a duplicate.
