### ISSUE TITLE
Retroactively check all users when a new filter is added

### ISSUE THREAD

**Issue by ammongit** [strinking/futaba#304]
When a new filter is added, we should be able to see if any existing users have names which cause the filter to be triggered. If this is the case, then they should be outputted to the filter log channels as if they were just changed.

This should be done in a backgrounded job to avoid delaying the command itself.

**Comment by robstolarz** [comment]
Are we sure we don't want to just do this in a cron and save ourselves the task queue / timers / etc?

**Comment by ammongit** [comment]
There's no point running jobs to check everybody's names if they haven't changed.

This just covers the other case: we trigger name filter checks whenever their name changes, so we should also trigger checks whenever the filters change.

**Comment by ammongit** [comment]
Also it occurred to me that we do not check names on join. We should do that here as well.
