### ISSUE TITLE
Allow user to be able to self dunce themselves

### ISSUE THREAD

**Issue by Ma-wa-re** [strinking/futaba#342]
Many users have recently wanted to dunce themselves to focus without distraction.
A command that allows them to do this would be good e.g. `!selfdunce`

**Comment by ammongit** [comment]
Remember to prevent using those commands when already dunced, as it could
be used to bypass other punishments. Additionally there should be a limit
on the time so you can trap yourself for a long time.

**Comment by Ma-wa-re** [comment]
Maybe another add a separate role for it would be the best way to deal with that.
That way it would not remove the admin one but it would still be good to have those checks?

**Comment by Ma-wa-re** [comment]
@ammongit What to you think about just having it be a timed based dunce only without a manual way to undunce?
With that they will just have to wait for the time to let them out and they will not be able to bypass other punishments.

**Comment by Ma-wa-re** [comment]
With a limit of 12 hours of being dunced as that would cover most working shifts that I can think of?
