### ISSUE TITLE
Make Text Filter Cog

### ISSUE THREAD

**Issue by Ma-wa-re** [strinking/futaba#9]
Make a cog to filter messages. Needs to have a guild wide filter list (and possibly a channel filter list that only applies to that channel)  that can words added to by admins and mods.
Admins and possibly mods should be immune to the filter and maybe a command to add user easily so they are also immune.
And if a way to add regex to the filter list and use that to filter would be a plus

**Comment by Ma-wa-re** [comment]
This needs #7 to be completed first before work can be done on i

**Comment by Ma-wa-re** [comment]
There should be two different events that can happen for a filtered word:
- Instant deletion
- Staff alert

If the word is to be instant deleted, the user is informed that their messages was deleted (with a copy of their message with the filtered word highlighted) and a message notifying staff

If the word is to be alerted to staff, a message is sent to the set staff alert channel with info about the message in question. The alert will have two reactions added to it, one will approve the message and the message in question will stay if selected, the other option will delete the message and inform the user that staff decided to remove their message

**Comment by MagnificentPako** [comment]
I would suggest adding support for homoglyphs, so people can't sneak in banned words like this `gаʏ`.

**Comment by ammongit** [comment]
How does that work? Is there an easy way to integrate it with regular expressions?

**Comment by MagnificentPako** [comment]
I'm not a python expert but I believe https://github.com/vhf/confusable_homoglyphs implements the functions needed to handle lookalike homoglyphs.

**Comment by ammongit** [comment]
Sounds good.
